using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace NanoKV.SerializationGenerator;

[Generator]
public sealed class BinarySerializerGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) =>
                    node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },

                transform: static (ctx, _) =>
                    GetClassSymbol(ctx))
            .Where(static symbol => symbol is not null);

        context.RegisterSourceOutput(classes, static (spc, symbol) =>
        {
            if (symbol is null)
                return;

            string source = GenerateSerializer(symbol);

            spc.AddSource(
                $"{symbol.Name}.BinarySerializer.g.cs",
                SourceText.From(source, Encoding.UTF8));
        });
    }

    private static INamedTypeSymbol? GetClassSymbol(
        GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;

        if (context.SemanticModel.GetDeclaredSymbol(classDeclaration)
            is not INamedTypeSymbol symbol)
        {
            return null;
        }

        bool hasAttribute = symbol.GetAttributes().Any(attribute =>
            attribute.AttributeClass?.ToDisplayString() ==
            "NanoKV.SerializationGenerator.GenerateBinarySerializerAttribute");

        return hasAttribute
            ? symbol
            : null;
    }

    private static string GenerateSerializer(INamedTypeSymbol type)
    {
        string namespaceName = type.ContainingNamespace.ToDisplayString();
        string className = type.Name;

        var properties = type.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public)
            .Where(p => !p.IsStatic)
            .Where(p => p.GetMethod is not null)
            .ToArray();

        var serializeBody = new StringBuilder();
        var deserializeBody = new StringBuilder();

        foreach (var property in properties)
        {
            string propertyName = property.Name;
            string propertyType = property.Type.ToDisplayString();

            switch (propertyType)
            {
                case "int":
                    {
                        serializeBody.AppendLine(
                            $"        writer.Write({propertyName});");

                        deserializeBody.AppendLine(
                            $"            {propertyName} = reader.ReadInt32(),");

                        break;
                    }

                case "string":
                    {
                        serializeBody.AppendLine(
                            $"        writer.Write({propertyName} ?? string.Empty);");

                        deserializeBody.AppendLine(
                            $"            {propertyName} = reader.ReadString(),");

                        break;
                    }

                case "System.DateTime":
                    {
                        serializeBody.AppendLine(
                            $"        writer.Write({propertyName}.Ticks);");

                        deserializeBody.AppendLine(
                            $"            {propertyName} = new global::System.DateTime(reader.ReadInt64()),");

                        break;
                    }

                default:
                    {
                        serializeBody.AppendLine(
                            $$"""        throw new global::System.NotSupportedException("Property '{{propertyName}}' has unsupported type '{{propertyType}}'.");""");

                        break;
                    }
            }
        }

        return $$"""
// <auto-generated />

namespace {{namespaceName}};

public partial class {{className}}
{
    public void SerializeToBinary(global::System.IO.Stream stream)
    {
        global::System.ArgumentNullException.ThrowIfNull(stream);

        using var writer = new global::System.IO.BinaryWriter(
            stream,
            global::System.Text.Encoding.UTF8,
            leaveOpen: true);

{{serializeBody}}
    }

    public byte[] SerializeToBinary()
    {
        using var stream = new global::System.IO.MemoryStream();

        SerializeToBinary(stream);

        return stream.ToArray();
    }

    public static {{className}} DeserializeFromBinary(
        global::System.IO.Stream stream)
    {
        global::System.ArgumentNullException.ThrowIfNull(stream);

        using var reader = new global::System.IO.BinaryReader(
            stream,
            global::System.Text.Encoding.UTF8,
            leaveOpen: true);

        return new {{className}}
        {
{{deserializeBody}}
        };
    }

    public static {{className}} DeserializeFromBinary(byte[] bytes)
    {
        global::System.ArgumentNullException.ThrowIfNull(bytes);

        using var stream = new global::System.IO.MemoryStream(bytes);

        return DeserializeFromBinary(stream);
    }
}
""";
    }
}